# Generated by Django 5.2.12 on 2026-03-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0003_datasetfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticMappingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'ai'), ('user', 'user')], default='ai', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_runs', to='datasets.dataset')),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantic_runs', to='datasets.datasetsheet')),
            ],
        ),
        migrations.CreateModel(
            name='SemanticMappingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=512)),
                ('semantic_label', models.CharField(choices=[('company_name', 'company_name'), ('person_name', 'person_name'), ('product_name', 'product_name'), ('quantity', 'quantity'), ('date', 'date'), ('datetime', 'datetime'), ('email', 'email'), ('phone', 'phone'), ('prefecture', 'prefecture'), ('city', 'city'), ('amount', 'amount'), ('amount_jpy', 'amount_jpy'), ('unit_price', 'unit_price'), ('category', 'category'), ('memo', 'memo'), ('count', 'count'), ('assignee', 'assignee'), ('department', 'department'), ('customer', 'customer'), ('product', 'product'), ('status', 'status'), ('unknown', 'unknown'), ('ignore', 'ignore')], default='unknown', max_length=32)),
                ('confidence', models.FloatField(default=0.5)),
                ('source', models.CharField(choices=[('ai', 'ai'), ('user', 'user')], default='ai', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_entries', to='datasets.datasetsheet')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='semantic_mapping.semanticmappingrun')),
            ],
        ),
    ]
