# Generated by Django 5.2.12 on 2026-03-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0003_datasetfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='queued', max_length=16)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiling_runs', to='datasets.dataset')),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiling_runs', to='datasets.datasetsheet')),
            ],
        ),
        migrations.CreateModel(
            name='ProfiledColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=512)),
                ('normalized_name', models.CharField(max_length=512)),
                ('inferred_dtype', models.CharField(max_length=32)),
                ('null_ratio', models.FloatField(default=0.0)),
                ('unique_ratio', models.FloatField(default=0.0)),
                ('sample_values', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiled_columns', to='datasets.datasetsheet')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='profiling.profilingrun')),
            ],
        ),
    ]
