# Generated by Django 5.2.12 on 2026-03-27 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=16)),
                ('required_columns', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('rule', 'rule'), ('ai', 'ai')], default='rule', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='datasets.dataset')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
