# Generated by Django 5.2.12 on 2026-04-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='未入力の場合は環境変数 OPENAI_API_KEY を使用します。', max_length=512, verbose_name='OpenAI API キー')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenAI API キー',
                'verbose_name_plural': 'OpenAI API キー',
            },
        ),
    ]
