# Generated by Django 5.2.12 on 2026-03-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RagChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(default='manual', max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tokens', models.JSONField(default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
