# Generated by Django 5.2.12 on 2026-04-06 06:05
#
# Step 3/4 初回単位: analysis_job → table_scope（後続で table_read_artifact 等へ拡張）
# review_session / normalized_dataset は含めない。

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=255)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_ref', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=32)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('current_stage', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_intelligence_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableScope',
            fields=[
                ('table_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(blank=True, max_length=255)),
                ('table_label', models.CharField(blank=True, max_length=255)),
                ('row_min', models.IntegerField(blank=True, null=True)),
                ('col_min', models.IntegerField(blank=True, null=True)),
                ('row_max', models.IntegerField(blank=True, null=True)),
                ('col_max', models.IntegerField(blank=True, null=True)),
                ('header_depth', models.IntegerField(blank=True, null=True)),
                ('left_stub_depth', models.IntegerField(blank=True, null=True)),
                ('detection_basis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_scopes', to='table_intelligence.analysisjob')),
            ],
            options={
                'db_table': 'table_scope',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['workspace_id', 'status', 'created_at'], name='analysis_jo_workspa_d0aff1_idx'),
        ),
        migrations.AddIndex(
            model_name='tablescope',
            index=models.Index(fields=['job'], name='table_scope_job_id_6c94df_idx'),
        ),
        migrations.AddIndex(
            model_name='tablescope',
            index=models.Index(fields=['workspace_id'], name='table_scope_workspa_764c60_idx'),
        ),
    ]
