# Generated by Django 5.2.12 on 2026-04-06 06:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_intelligence', '0002_artifacts_metadata_evaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanReviewSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('RESOLVED', 'RESOLVED'), ('CLOSED_UNRESOLVED', 'CLOSED_UNRESOLVED')], default='OPEN', max_length=32)),
                ('review_required_snapshot', models.BooleanField(default=False)),
                ('review_points_snapshot', models.JSONField(blank=True, default=list)),
                ('resolution_grade', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_review_sessions', to=settings.AUTH_USER_MODEL)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_review_sessions', to='table_intelligence.analysismetadata')),
            ],
            options={
                'db_table': 'human_review_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HumanReviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=255)),
                ('answer_value', models.JSONField(blank=True, default=dict)),
                ('answered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_review_answers', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_rows', to='table_intelligence.humanreviewsession')),
            ],
            options={
                'db_table': 'human_review_answer',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuppressionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=255)),
                ('suppression_level', models.CharField(choices=[('SUGGESTION_BLOCKED', 'SUGGESTION_BLOCKED'), ('SUGGESTION_LIMITED', 'SUGGESTION_LIMITED'), ('SUGGESTION_ALLOWED_WITH_CAUTION', 'SUGGESTION_ALLOWED_WITH_CAUTION')], max_length=64)),
                ('suppression_reason', models.TextField(blank=True)),
                ('suppressed_targets', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppression_records', to='table_intelligence.humanreviewsession')),
            ],
            options={
                'db_table': 'suppression_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='humanreviewsession',
            index=models.Index(fields=['workspace_id'], name='human_revie_workspa_92133e_idx'),
        ),
        migrations.AddIndex(
            model_name='humanreviewsession',
            index=models.Index(fields=['metadata'], name='human_revie_metadat_b80744_idx'),
        ),
        migrations.AddIndex(
            model_name='humanreviewanswer',
            index=models.Index(fields=['session'], name='human_revie_session_1e0606_idx'),
        ),
        migrations.AddIndex(
            model_name='suppressionrecord',
            index=models.Index(fields=['session'], name='suppression_session_5c7ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='suppressionrecord',
            index=models.Index(fields=['workspace_id'], name='suppression_workspa_e04fc0_idx'),
        ),
    ]
