# Generated by Django 5.2.12 on 2026-04-06 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_intelligence', '0003_review_sessions_suppression'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionSet',
            fields=[
                ('suggestion_run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=255)),
                ('analysis_candidates', models.JSONField(blank=True, default=list)),
                ('suppression_applied', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suggestion_sets', to=settings.AUTH_USER_MODEL)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_sets', to='table_intelligence.analysismetadata')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_sets', to='table_intelligence.tablescope')),
            ],
            options={
                'db_table': 'suggestion_set',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace_id'], name='suggestion__workspa_1f1612_idx'), models.Index(fields=['metadata'], name='suggestion__metadat_dce3d7_idx')],
            },
        ),
    ]
