# Generated by Django 5.2.12 on 2026-04-06 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_intelligence', '0005_analysis_job_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactRelation',
            fields=[
                ('relation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=255)),
                ('relation_type', models.CharField(db_index=True, max_length=64)),
                ('from_artifact_type', models.CharField(max_length=64)),
                ('from_artifact_id', models.CharField(max_length=64)),
                ('to_artifact_type', models.CharField(max_length=64)),
                ('to_artifact_id', models.CharField(max_length=64)),
                ('context_job_id', models.UUIDField(blank=True, db_index=True, help_text='この edge を記録した成果物生成ジョブ（任意・FK なし）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'artifact_relation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace_id', 'relation_type', 'created_at'], name='artifact_re_workspa_0be6c4_idx'), models.Index(fields=['from_artifact_type', 'from_artifact_id'], name='artifact_re_from_ar_6e2e21_idx'), models.Index(fields=['to_artifact_type', 'to_artifact_id'], name='artifact_re_to_arti_85f0cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('context_job_id', 'relation_type', 'from_artifact_type', 'from_artifact_id', 'to_artifact_type', 'to_artifact_id'), name='uniq_artifact_relation_edge_per_job')],
            },
        ),
    ]
