# Generated by Django 5.2.12 on 2026-04-07 03:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_intelligence', '0007_judgment_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableReadArtifact',
            fields=[
                ('artifact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=255)),
                ('cells', models.JSONField(blank=True, default=dict, help_text='006 cells（001 稀疏表現など）。')),
                ('merges', models.JSONField(blank=True, default=list, help_text='006 merges[]。')),
                ('parse_warnings', models.JSONField(blank=True, default=list, help_text='006 parse_warnings[]（空配列可）。')),
                ('artifact_version', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_artifacts', to='table_intelligence.analysisjob')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_artifacts', to='table_intelligence.tablescope')),
            ],
            options={
                'db_table': 'table_read_artifact',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace_id'], name='table_read__workspa_7bd9e7_idx'), models.Index(fields=['table', 'is_latest'], name='table_read__table_i_c3d4cb_idx'), models.Index(fields=['job'], name='table_read__job_id_a7b28e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('table',), name='uniq_table_read_artifact_latest_per_table')],
            },
        ),
    ]
